EZA_DEFAULT_OPTIONS='--header --long --time-style long-iso --git-repos --git --icons --octal-permissions --classify --hyperlink --group --mounts --extended'
alias l='eza $EZA_DEFAULT_OPTIONS'
alias ls='eza $EZA_DEFAULT_OPTIONS'
alias la='eza -a $EZA_DEFAULT_OPTIONS'
alias lr='eza -R $EZA_DEFAULT_OPTIONS'
alias lsr='eza -R $EZA_DEFAULT_OPTIONS'
alias lar='eza -Ra $EZA_DEFAULT_OPTIONS'
