alias v='vim'

alias ll='ls -lhA'
alias sl='ls'
alias l='ls -CF'
alias la='ls -A'

alias mkdir='mkdir -p'
alias top='htop'
alias grep='grep --ignore-case --color=auto'

alias caf='ls -Uba1 | wc -l'
alias cf='ls -Ub1 | wc -l'

alias SeedBox='ssh -D 8080 -o LogLevel=ERROR SeedBox'
alias ArchServer='ssh ArchServer'
