#
# ~/.bash_profile
#

# Load .profile, containing login, non-bash related initializations.
source /etc/config/home/profile

# Load .bashrc, containing non-login related bash initializations.
source /etc/config/home/bashrc
