#!/usr/bin/env bash

# cf - fuzzy cd from anywhere
# ex: cf word1 word2 ... (even part of a file name)
# zsh autoload function
file="$(locate -Ai -0 "$@" | grep -z -vE '~$' | fzf --read0 -0 -1)"

if [[ -n $file ]]
then
    if [[ -d $file ]]
    then
       cd -- "$file" || exit
    else
       cd -- "${file:h}" || exit
    fi
fi
