#!/usr/bin/env bash

LOC="$HOME/.local/share/nvim/site/autoload/plug.vim"
if [ ! -f "$LOC" ]; then
    curl -fLo "$LOC" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ $# -le 1 ]; then
    nvim "$@"
    exit $?
fi

path=$1
parent_dir="$(dirname $path)"
if [[ ! -d "$parent_dir" ]]; then
    yes-no "$parent_dir doesn't exist. Would you like to create it?" || \
        exit 1
fi
mkdir -p "$parent_dir"
nvim $path
