#!/usr/bin/env bash

if [ $# -lt 2 ]; then
    err "2 arguments required"
    exit 1
fi
url=$1
cert_str="$(openssl s_client -showcerts -connect ${url}:443 < /dev/null)"
echo "$cert_str" | awk "/BEGIN CERTIFICATE/,/END CERTIFICATE/{ if(/BEGIN CERTIFICATE/){a++}; out=\"$2/cert\"a\".crt\"; print >out}"
