#!/usr/bin/env bash

PROMPT=$1
while true; do
    read -r -n 1 -p "$PROMPT (y/N): " answer
    case ${answer:0:1} in
        y|Y )
            exit 0
        ;;
        * )
            exit 1
        ;;
    esac
done
