-- function FixGruvbox()
--   local delete = "#8a5f60" -- Mixed from #f79e9e
--   local add = "#64966B" -- Mixed from #9ef7a8
--   local change = "#959666" -- Mixed from #f7f69e
--   -- TODO: WTF is DiffText? I cannot figure it out by context.
--   local text = "#648a97" -- Mixed from #9ee1f7
--
--   vim.api.nvim_set_hl(0, "DiffviewDiffAddAsDelete", { bg = delete })
--   vim.api.nvim_set_hl(0, "DiffDelete", { bg = delete })
--   vim.api.nvim_set_hl(0, "DiffviewDiffDelete", { bg = delete })
--   vim.api.nvim_set_hl(0, "DiffAdd", { bg = add })
--   vim.api.nvim_set_hl(0, "DiffChange", { bg = change })
--   vim.api.nvim_set_hl(0, "DiffText", { bg = text })
-- end
-- FixGruvbox()
--
-- vim.api.nvim_create_autocmd("ColorScheme", { pattern = { "gruvbox" }, callback = FixGruvbox })
