#!/usr/bin/env bash

# -- Externally Defined Aliases ------------------------------------------------
ALIAS_FILES="$DOTFILES/bash/aliases"
if [[ -d "$ALIAS_FILES" ]]; then
  for file in $(fd -t f . "$ALIAS_FILES"); do
    source "$file"
  done
else
  echo "Failed to load bash functions" >&2
fi

# Check if work bash aliases exists
WORK_ALIASES="$HOME/.bash_aliases.work"
if [ -f "$WORK_ALIASES" ]; then
  source "$WORK_ALIASES"
fi

# -- General Helpers -----------------------------------------------------------
alias reload='source $HOME/.bashrc'
alias j='just'
alias e='$EDITOR'
alias edit='$EDITOR'
alias cp='xcp'
alias mkdir='mkdir -p'
alias docker='podman'
alias cat='bat'
# TODO: blesh uses the `time` command and when this alias is enabled it runs
# hyperfine which results in extremely slow commands due to running multiple
# benchmarks. Figure out how to make blesh use the time binary.
# alias time='hyperfine'
alias benchmark='hyperfine'

function ntemp() {
  tmp="$(mktemp -d)"
  cd "$tmp" || exit 1
}

# -- Bash Scripting ------------------------------------------------------------
# Don't set -e in this alias. It will cause the interactive shell you called the
# script with to exit if the script fails for any reason.
alias debug-bash='set -uxo pipefail'
alias debug-bash-undo='set +uxo pipefail'

# -- Pacman --------------------------------------------------------------------
alias installed='pacman -Qe'

# -- Navigation ----------------------------------------------------------------
alias dotfiles='cd $DOTFILES'
alias home='cd $HOME'
alias cdd='cd ..'

# -- Quick Config Access -------------------------------------------------------
alias conf-aliases='$EDITOR $HOME/.bash_aliases'
alias conf-bashrc='$EDITOR $HOME/.bashrc'
alias conf-tmux='$EDITOR $HOME/.config/tmux/tmux.conf'

# -- Git -----------------------------------------------------------------------
alias g='git status'
alias ca='commit-all'
alias pa='push-all'
alias aa='add-all'
alias st='git status --short --branch'
alias ig="find . -not -path './.git/*' | git check-ignore --stdin"
alias push='git push'
alias pull='git pull'
alias glog='git log'

# -- Programming ---------------------------------------------------------------
alias lf="fd -t f -x dos2unix {} \;"
